#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
module load python3/3.10.5 samtools rseqc/5.0.1
geneBody_coverage.py \
--input=accepted_hits.bam,accepted_hits.bami \
--refgene=/project/bf528/project_2/reference/annot/mm9.bed \
--out-prefix=gbcov_out

inner_distance.py \
--input=accepted_hits.bam,accepted_hits.bami \
--refgene=/project/bf528/project_2/reference/annot/mm9.bed \
--out-prefix=indist_out

bam_stat.py \
--input=accepted_hits.bam,accepted_hits.bami
echo "Job finished: $(date +%F)"
